[package]
name = "purescript-corefn"
version = "0.1.0"
authors = ["Utkarsh Kukreti <utkarshkukreti@gmail.com>"]
description = "A parser for PureScript's corefn JSON representation."
license = "MIT"

[dependencies]
serde = "1.0.75"
serde_derive = "1.0.75"
serde_json = "1.0.26"
